ibireme/yyjson

README.md
Follow README and you will see:
```
$ cmake .. -DYYJSON_BUILD_TESTS=1
-- No build type selected, default to: Release
-- Configuring done
-- Generating done
CMake Warning:
Manually-specified variables were not used by the project:
YYJSON_BUILD_TESTS
```
=> fix(docs): fix cmake cannot build test problem

doc/API.md
Fixing some minor typos in the API documentation.
=> Fix some typos in the API documentation for allocators.

CMakeLists.txt
This allows calling `make install`, or `ninja install` after configuring a project with cmake.
=> cmake: support install target

CMakeLists.txt, src/yyjson.h
There was a warning when promoting float to double in `yyjson_mut_arr_with_float`
=> Fix compilation with -Wdouble-promotion

src/yyjson.c
This is a minor change to prevent leaking file descriptors to fork+exec child processes.
=> Add glibc extension to enable O_CLOEXEC in fopen ('e' mode)

CMakeLists.txt
- Fix yyjson.dll installation on Windows;
- Intall yyjson-config*.cmake to make it easy to integrate with CMake projects;
=> CMake: Improve installation

src/yyjson.c
Hi! I was trying to add `yyjson` to `vcpkg`: https://github.com/microsoft/vcpkg/pull/17201
The CI system of `vcpkg` reports a build error on `x64-uwp` and `arm-uwp`. The failure log can be seen here: https://dev.azure.com/vcpkg/public/_build/results?buildId=51884&view=artifacts&pathAsName=false&type=publishedArtifacts
> error C4700: uninitialized local variable 'alc' used
https://github.com/ibireme/yyjson/blob/c3a1f1f54a517dc15ba8670d969c0acdfabcd039/src/yyjson.c#L5060-L5087
`alc` is assigned a value in line 5086, but it might be referenced in line 5085.
=> Fix MSVC build error on UWP

src/yyjson.h
This warning lights up a few times in the header when compiling with MSVC 2015. It was turned off by default in later versions due to noise.
=> Suppress C4800 warning (MSVC 2015 and earlier)

src/yyjson.h
make `yyjson_mut_arr_iter` consistent with `yyjson_mut_obj_iter`:
- rename `prev` field to `pre`
- reorder fields
initialize all fields in `iter_init`
=> yyjson_mut_arr_iter struct changes

src/yyjson.h
`unsafe_yyjson_mut_obj_add` already has it
=> remove extra call to unsafe_yyjson_set_len

src/yyjson.h
`yyjson_mut_arr_rotate` allows rotating values in the array.
For example [1,2,3] --> rotate 2 --> [3,1,2]
Rotate 0 doesn't change the array, rotate for `arr_len` or more is not allowed.
=> Add rotate method for yyjson_mut_arr

src/yyjson.h
Unless there's a specific reason not to do it, I think that the type of `yyjson_mut_val` should be checked, that it is an array, before modifying in yyjson_mut_arr functions.
For yyjson_mut_obj the type is always checked.
For yyjson_val array the type is also already checked.
=> Check that the type of value is array before modifying it

src/yyjson.h
We don't need traversing the whole object for insertion at 0 index. We can just restore the previous `uni.ptr`.
Also don't call `obj_rotate` when `len` was zero.
=> yyjson_mut_obj_insert: optimize insertion at 0 index

src/yyjson.h, test/test_json_mut_val.c
Added tests for `yyjson_mut_obj_insert`, `yyjson_mut_obj_rotate` and `yyjson_mut_arr_rotate`.
Fixed issues with `yyjson_mut_obj_insert`, my bad, previously it correctly inserted a new key-value at specified position, but it was messing the order of other key-pairs. The correct way should be like this: 
- rotate to specified index
- add a new key-value
- restore the previous object tail
=> Add tests and fix yyjson_mut_obj_insert

CMakeLists.txt
this makes so libyyjson.so.0.4.0 is created and libyyjson.so is a
symlink to it
=> set library version so shared library is created with soname

src/yyjson.c
Hello.
All four commits have descriptions with reasoning to changes in them.
- This was most likely a copy-pasta when `mut_copy` functions were introduced.
`i_val` and `i_doc` names were blindly copied from the immutable functions implementations.
When working with `yyjson_mut_doc` and `yyjson_mut_val`, the prefix clearly should be `m_` instead of `i_`.
- When creating a doc copy, we should check that its root is not NULL beforehand to avoid unnececary allocation of new doc, since it'll be destroyed right away.
- Renamed `unsafe_yyjson_mut_ctn_mut_copy` to `unsafe_yyjson_mut_val_mut_copy` since it works with
any value type, not just containers.
- Rewritten `unsafe_yyjson_mut_val_mut_copy` with common logic for object and array traversal.
The mutable object or array stores all sub-values …
=> Changes in mut_copy functions

src/yyjson.c, src/yyjson.h, test/test_json_mut_val.c
Rewrite `yyjson_mut_equals` using qsort+bsearch
when comparing JSON objects, so that the complexity
is loglinear now instead of quadratic.
The keys from the first object are sorted in malloc'ed array.
The keys from the second object are searched in this array
and their values are compared.
Also this function supports YYJSON_TYPE_RAW now
(raw numbers can only be compared with other raw numbers as of now).
Added more tests for `yyjson_mut_equals`.
When objects contain duplicate keys, the result is inaccurate.
=> yyjson_mut_equals refactoring

src/yyjson.c, src/yyjson.h, test/test_json_val.c
It is basically the same as `yyjson_mut_equals` but with slightly different object and array traversal.
Added `unsafe_yyjson_num_equals` and `unsafe_yyjson_str_equals` since the comparison of
numbers and strings is common for mutable and immutable values.
Added tests for `yyjson_equals`.
Also fixed `yyjson_obj_iter_init`.
When iter initialization fails, we should zero all bytes in iter struct,
like it is done in all other iter functions but was missing in this one.
Otherwise compiler gives a lot of `maybe-uninitialized` warnings.
=> Add yyjson_equals

src/yyjson.c, src/yyjson.h
I need creating raw values when their contents is already allocated in the doc, so I don't need extra copying.
I added 4 raw values creation functions, which are basically the same as `mut_str` functions, except
the value type is YYJSON_TYPE_RAW.
Also fixed writing raw values in `mut_val_write_opts`, seems like the raw values support was forgotten there.
=> Raw values fixes and improvements

src/yyjson.c, src/yyjson.h
I've been using this patch for months in my project, since I don't need json reader failing when there are invalid suquences in json strings.
Can we add a new option `YYJSON_READ_ALLOW_INVALID_UNICODE` (optional via `YYJSON_DISABLE_NON_STANDARD`) to allow parsing invalid unicode data?
=> Add option to allow reading invalid unicode

doc/BuildAndTest.md
yyjson is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for yyjson and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build yyjson, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here](https://github.com/microsoft/vcpkg/blob/master/ports/yyjson/portfile.cmake) is what the port script looks like. We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

src/yyjson.h
Write flag type was using read flag type. Not like it matters since they're just integers but for consistency sake.
=> Wrong write flag type.

src/yyjson.c, src/yyjson.h, test/test_number.c
I really like the yyjson `read_number` implementation and want to use it in my projects. The problem is that the current implementation is a static function which can't be used from other code.
I've added a simple wrapper `unsafe_yyjson_read_number` around `read_number` function, which parses number from the memory buffer into `yyjson_val` (or `yyjson_mut_val`) variable.
=> Add read_number public functions

CHANGELOG.md, src/yyjson.h, test/test_json_pointer.c
This PR adds the following convenience functions that get a value from `yyjson_doc` as specified by a JSON Pointer:
```
yyjson_get_bool_pointer()
yyjson_get_uint_pointer()
yyjson_get_sint_pointer()
yyjson_get_real_pointer()
yyjson_get_num_pointer()
yyjson_get_str_pointer()
```
Additionally, these functions allow the caller to disambiguate non-existing or type-mismatches from actual values of `false`, `0` and `0.0`, which is ambiguous using by their non-pointer variants (`yyget_get_bool()`, `yyjson_get_uint()`,...).
Tests included.
=> Add functions to get type-specific values specified by JSON Pointer

src/yyjson.h, test/test_json_pointer.c
In #116 the functions do not follow the API naming conventions.  Specifically, they accepted `yyjson_doc` but did not include `doc` in their name.
On further consideration, these functions would be more flexible if they accepted `yyjson_val` instead of `yyjson_doc` as one can always use `yyjson_doc_get_root()` and therefore support more use cases.
This PR changes the functions to accept `yyjson_val` instead of `yyjson_doc`.
=> Convert yyjson_get_TYPE_pointer() routines to accept `yyjson_val`

src/yyjson.c
Modify the Merge Patch logic to insert new additions to an object at the end of the object.
While technically a JSON object is an "unordered set of name/value pairs", it is nice to be able to control the order in some edge cases (my case is matching a specification for maximum clarity).  Further, it is logical that when adding new key/value pairs to an object that they would be added at the end, which is nicely done by `yyjson_mut_obj_add()` and friends.
The logic of `yyjson_merge_patch()` and `yyjson_mut_merge_patch()` lead to additions to objects going before the key/value pairs already existing in the object that are unmodified by the patch.
This PR inverts the order of adding values to the new structure such that modified values are added after unmodified values.
I initially tried …
=> Add new keys at end of object with Merge Patch

src/yyjson.h
Unused params / assignment within conditional expression.
=> Fix for warnings on msvc/W4

README.md
Seems more and more package managers tends to support yyjson, add a badge for easier tracking
=> README: add packaging status

CMakeLists.txt
Hi!
I've noticed that the CMake script overwrites the value of `CMAKE_CONFIGURATION_TYPES` for multi-config CMake generators. That effectively locks the configuration list to Debug and Release for CMake projects that add `yyjson` as a dependency with `add_subdirectory` (either directly, with `FetchContent` or by any other means). In my case I would like to keep the default value of `CMAKE_CONFIGURATION_TYPES` which has more configurations
The fix is to avoid changing `CMAKE_BUILD_TYPE` or `CMAKE_CONFIGURATION_TYPES` if yyjson is not the root CMake project. As far as I can see those variables are meant to be set only when building the library itself (but let me know if that's not correct)
Tested by generating and compiling `yyjson` with Visual Studio on Windows, both Debug and Release …
=> Don't overwrite CMake configuration types if yyjson is used as a dependency

README.md
Hi mate,
thanks for your great work!
We are developing a C++ library for serialization, deserialization and validation through reflection. It includes things like automatic field name retrieval from structs and enums.
The JSON part is based on YYJSON, so your work is front and center for what we do here.
So I wonder whether you could include it in your "build with YYJSON" section.
=> Include reflect-cpp

src/yyjson.h
Similar to `yyjson_mut_obj_add_strcpy`, in fact, the `val` & `len` in `yyjson_mut_obj_add_strncpy` have already been assigned values 
and do not need to have their lifetimes guaranteed.
https://github.com/ibireme/yyjson/blob/0eca326fe57aeeb866e6f04c9ef9ea9f8343157e/src/yyjson.h#L6963-L6974
The call to `unsafe_yyjson_mut_strncpy` in the above code also proves this point.
=> Correct the error in the comment for unsafe_yyjson_mut_strncpy

src/yyjson.c
`json_read_flag` and `json_write_flag` are both typedef'ed to `uint32_t`, but for good sense, the parameter in `get_enc_table_with_flag` should be `json_write_flag`, not `json_read_flag`
=> Parameter of get_enc_table_with_flag is json_read_flag, should be json_write_flag

README.md
Hi, we have created a Julia binding for yyjson, and it is now available in the official Julia registries under the name [YYJSON](https://github.com/bhftbootcamp/YYJSON.jl) (will be [registered](https://github.com/JuliaRegistries/General/pull/115576) in 72 hours). Thanks for creating such a great library!
=> Add Julia bindings for yyjson

src/yyjson.c
fixes this warning:
```
[44/110] Building C object CMakeFiles/common.dir/ext/yyjson/src/yyjson.c.obj
D:/work-pps/yyjson/src/yyjson.c:4420:18: warning: 'f64_pow10_table' defined but not used [-Wunused-const-variable=]
4420 | static const f64 f64_pow10_table[] = {
|                  ^~~~~~~~~~~~~~~
```
=> Fix warning: 'f64_pow10_table' defined but not used

doc/API.md, src/yyjson.c, src/yyjson.h, test/test_err_code.c, test/test_json_reader.c
simdjson also skips UTF-8 BOM before parsing: https://github.com/simdjson/simdjson/blob/v3.12.3/include/simdjson/generic/ondemand/parser-inl.h#L54
=> Add a read option to allow UTF-8 BOM

CMakeLists.txt
In CMake 3.27 and above, there will be a compatibility warning for CMake versions below 3.5.
In CMake 4.0, there will be a compatibility warning for versions below 3.10.
Therefore, use the `min...max` approach to eliminate these warnings. This way, support for older versions of CMake can still be retained.
References:
- https://github.com/vector-of-bool/cmrc/pull/48
- https://github.com/open-source-parsers/jsoncpp/pull/1499
- https://github.com/zeromq/libzmq/pull/4776
=> Fix CMake deprecation warning

CMakeLists.txt, doc/API.md, src/yyjson.c, src/yyjson.h, test/test_err_code.c, test/test_json_reader.c, test/util/yy_test_utils.c, test/util/yy_test_utils.h
This is an implementation of incremental read.
Reading a very large JSON document can freeze the program for a short while. If
this is not acceptable, incremental reading can be used.
Incremental reading is recommended only for large documents and only when the
program needs to be responsive. Incremental reading is slightly slower than
`yyjson_read()` and `yyjson_read_opts()`.
To read a large JSON document incrementally:
1. Call `yyjson_incr_new()` to create the state for incremental reading.
2. Call `yyjson_incr_read()` repeatedly.
3. Call `yyjson_incr_free()` to free the state.
A new error code `YYJSON_READ_ERROR_MORE` indicates incremental read is incomplete and can be resumed.
Conditional compilation is possible with `-DYYJSON_DISABLE_INCREMENTAL=ON`/`OFF`.
Example code:
```C
const …
```
=> Incremental read
